### ISSUE TITLE
Nom du repo

### ISSUE THREAD

**Issue by tdaron** [EPLStudents/Notions#1]
Le nom est pas un peu trop similaire au site Notion ce qui l'empêchera de ressortir dans des recherches Google ?

(C'est mon avis perso haha)

(Caillou au rapport, j'ai changé d'username github entre temps ^^)

Pour faire une suggestion, pourquoi pas EPLGuide ou EPLWiki ?

**Comment by Hokkaydo** [comment]
J'aime bien EPLWiki
Je pensais pas que quelqu'un trouverait déjà le repo, faut que je fasse encore quelques tests

**Comment by tdaron** [comment]
> J'aime bien EPLWiki
> Je pensais pas que quelqu'un trouverait déjà le repo, faut que je fasse encore quelques tests

Ahaha no soucis, je passe juste un peu trop de temps sur Github je l'ai vu dans mon 'feed' si on peut appeler ça comme ça
