### ISSUE TITLE
Unable to compile LaTeX due to unstandard character

### ISSUE THREAD

**Issue by Tfloow** [EPLStudents/Notions#4]
Emoji will make the vanilla latex compile fail. We could be either using a specific font to render emoji and run xeLaTeX or add support in the preamble for those unicode character.

**Comment by Hokkaydo** [comment]
That's a good point. I didn't run the LaTeX builder after adding emojis. It's something to consider, I'll check on it

**Comment by Hokkaydo** [comment]
Fixed in 61701a4

**Comment by Tfloow** [comment]
Just add to the requirements the Symbola font maybe

**Comment by Hokkaydo** [comment]
Is it not included by default?

**Comment by Tfloow** [comment]
Nope I had to download the font at this link https://drive.google.com/file/d/1SQaPD1LAg_hY6YO35LRWSaL-3agAURr6/view even though I have the full TeX install on Ubuntu

**Comment by Hokkaydo** [comment]
fixed in [903d797](https://github.com/EPLStudents/EPLWiki/commit/903d797dd1297aa106ed315f2f0cbc593b6d870e)
